// Starter catalog of commonly prescribed medicines (India-oriented names).
// This is intentionally a curated seed, not exhaustive — import a larger CSV
// into the `medicines` collection later to expand coverage. Each entry:
//   [name, generic, form]
module.exports = [
  ["Paracetamol", "Paracetamol", "tablet"],
  ["Paracetamol 500mg", "Paracetamol", "tablet"],
  ["Paracetamol 650mg", "Paracetamol", "tablet"],
  ["Dolo 650", "Paracetamol", "tablet"],
  ["Crocin", "Paracetamol", "tablet"],
  ["Calpol", "Paracetamol", "syrup"],
  ["Ibuprofen", "Ibuprofen", "tablet"],
  ["Brufen 400", "Ibuprofen", "tablet"],
  ["Combiflam", "Ibuprofen + Paracetamol", "tablet"],
  ["Aspirin", "Aspirin", "tablet"],
  ["Diclofenac", "Diclofenac", "tablet"],
  ["Voveran", "Diclofenac", "tablet"],
  ["Aceclofenac", "Aceclofenac", "tablet"],
  ["Naproxen", "Naproxen", "tablet"],
  ["Nimesulide", "Nimesulide", "tablet"],
  ["Tramadol", "Tramadol", "tablet"],
  ["Amoxicillin", "Amoxicillin", "capsule"],
  ["Amoxicillin + Clavulanic Acid", "Amoxicillin + Clavulanic Acid", "tablet"],
  ["Augmentin 625", "Amoxicillin + Clavulanic Acid", "tablet"],
  ["Azithromycin", "Azithromycin", "tablet"],
  ["Azithral 500", "Azithromycin", "tablet"],
  ["Cefixime", "Cefixime", "tablet"],
  ["Cefpodoxime", "Cefpodoxime", "tablet"],
  ["Ceftriaxone", "Ceftriaxone", "injection"],
  ["Cephalexin", "Cephalexin", "capsule"],
  ["Ciprofloxacin", "Ciprofloxacin", "tablet"],
  ["Levofloxacin", "Levofloxacin", "tablet"],
  ["Ofloxacin", "Ofloxacin", "tablet"],
  ["Doxycycline", "Doxycycline", "capsule"],
  ["Metronidazole", "Metronidazole", "tablet"],
  ["Flagyl 400", "Metronidazole", "tablet"],
  ["Clarithromycin", "Clarithromycin", "tablet"],
  ["Norfloxacin", "Norfloxacin", "tablet"],
  ["Clindamycin", "Clindamycin", "capsule"],
  ["Fluconazole", "Fluconazole", "tablet"],
  ["Ketoconazole", "Ketoconazole", "tablet"],
  ["Albendazole", "Albendazole", "tablet"],
  ["Ivermectin", "Ivermectin", "tablet"],
  ["Acyclovir", "Acyclovir", "tablet"],
  ["Cetirizine", "Cetirizine", "tablet"],
  ["Levocetirizine", "Levocetirizine", "tablet"],
  ["Loratadine", "Loratadine", "tablet"],
  ["Fexofenadine", "Fexofenadine", "tablet"],
  ["Allegra 120", "Fexofenadine", "tablet"],
  ["Montelukast", "Montelukast", "tablet"],
  ["Montelukast + Levocetirizine", "Montelukast + Levocetirizine", "tablet"],
  ["Chlorpheniramine Maleate", "Chlorpheniramine Maleate", "tablet"],
  ["Pheniramine", "Pheniramine", "tablet"],
  ["Pantoprazole", "Pantoprazole", "tablet"],
  ["Pan 40", "Pantoprazole", "tablet"],
  ["Omeprazole", "Omeprazole", "capsule"],
  ["Esomeprazole", "Esomeprazole", "tablet"],
  ["Rabeprazole", "Rabeprazole", "tablet"],
  ["Ranitidine", "Ranitidine", "tablet"],
  ["Domperidone", "Domperidone", "tablet"],
  ["Ondansetron", "Ondansetron", "tablet"],
  ["Emeset", "Ondansetron", "tablet"],
  ["Digene", "Antacid", "tablet"],
  ["Sucralfate", "Sucralfate", "syrup"],
  ["Dicyclomine", "Dicyclomine", "tablet"],
  ["Drotaverine", "Drotaverine", "tablet"],
  ["Loperamide", "Loperamide", "tablet"],
  ["ORS", "Oral Rehydration Salts", "sachet"],
  ["Lactulose", "Lactulose", "syrup"],
  ["Bisacodyl", "Bisacodyl", "tablet"],
  ["Metformin", "Metformin", "tablet"],
  ["Metformin 500mg", "Metformin", "tablet"],
  ["Glimepiride", "Glimepiride", "tablet"],
  ["Glimepiride + Metformin", "Glimepiride + Metformin", "tablet"],
  ["Gliclazide", "Gliclazide", "tablet"],
  ["Sitagliptin", "Sitagliptin", "tablet"],
  ["Vildagliptin", "Vildagliptin", "tablet"],
  ["Teneligliptin", "Teneligliptin", "tablet"],
  ["Insulin", "Insulin", "injection"],
  ["Amlodipine", "Amlodipine", "tablet"],
  ["Telmisartan", "Telmisartan", "tablet"],
  ["Telmisartan + Amlodipine", "Telmisartan + Amlodipine", "tablet"],
  ["Losartan", "Losartan", "tablet"],
  ["Ramipril", "Ramipril", "tablet"],
  ["Enalapril", "Enalapril", "tablet"],
  ["Atenolol", "Atenolol", "tablet"],
  ["Metoprolol", "Metoprolol", "tablet"],
  ["Bisoprolol", "Bisoprolol", "tablet"],
  ["Hydrochlorothiazide", "Hydrochlorothiazide", "tablet"],
  ["Furosemide", "Furosemide", "tablet"],
  ["Atorvastatin", "Atorvastatin", "tablet"],
  ["Rosuvastatin", "Rosuvastatin", "tablet"],
  ["Clopidogrel", "Clopidogrel", "tablet"],
  ["Salbutamol", "Salbutamol", "inhaler"],
  ["Levosalbutamol", "Levosalbutamol", "syrup"],
  ["Budesonide", "Budesonide", "inhaler"],
  ["Theophylline", "Theophylline", "tablet"],
  ["Ambroxol", "Ambroxol", "syrup"],
  ["Bromhexine", "Bromhexine", "syrup"],
  ["Dextromethorphan", "Dextromethorphan", "syrup"],
  ["Guaifenesin", "Guaifenesin", "syrup"],
  ["Prednisolone", "Prednisolone", "tablet"],
  ["Dexamethasone", "Dexamethasone", "tablet"],
  ["Hydrocortisone", "Hydrocortisone", "injection"],
  ["Betamethasone", "Betamethasone", "cream"],
  ["Vitamin D3", "Cholecalciferol", "sachet"],
  ["Calcium + Vitamin D3", "Calcium + Vitamin D3", "tablet"],
  ["Vitamin B Complex", "Vitamin B Complex", "tablet"],
  ["Vitamin C", "Ascorbic Acid", "tablet"],
  ["Folic Acid", "Folic Acid", "tablet"],
  ["Iron + Folic Acid", "Ferrous + Folic Acid", "tablet"],
  ["Methylcobalamin", "Methylcobalamin", "tablet"],
  ["Zinc", "Zinc", "tablet"],
  ["Multivitamin", "Multivitamin", "tablet"],
  ["Pantoprazole + Domperidone", "Pantoprazole + Domperidone", "capsule"],
  ["Thyroxine", "Levothyroxine", "tablet"],
  ["Thyronorm", "Levothyroxine", "tablet"],
  ["Diazepam", "Diazepam", "tablet"],
  ["Alprazolam", "Alprazolam", "tablet"],
  ["Clonazepam", "Clonazepam", "tablet"],
  ["Amitriptyline", "Amitriptyline", "tablet"],
  ["Sertraline", "Sertraline", "tablet"],
  ["Escitalopram", "Escitalopram", "tablet"],
  ["Gabapentin", "Gabapentin", "tablet"],
  ["Pregabalin", "Pregabalin", "capsule"],
  ["Carbamazepine", "Carbamazepine", "tablet"],
  ["Levetiracetam", "Levetiracetam", "tablet"],
  ["Mefenamic Acid", "Mefenamic Acid", "tablet"],
  ["Meftal Spas", "Mefenamic Acid + Dicyclomine", "tablet"],
  ["Serratiopeptidase", "Serratiopeptidase", "tablet"],
  ["Chymotrypsin", "Trypsin + Chymotrypsin", "tablet"],
  ["Diclofenac Gel", "Diclofenac", "gel"],
  ["Mupirocin", "Mupirocin", "cream"],
  ["Clotrimazole", "Clotrimazole", "cream"],
  ["Silver Sulfadiazine", "Silver Sulfadiazine", "cream"],
  ["Neosporin", "Neomycin", "ointment"],
  ["Povidone Iodine", "Povidone Iodine", "ointment"],
  ["Xylometazoline", "Xylometazoline", "nasal drops"],
  ["Otrivin", "Xylometazoline", "nasal drops"],
  ["Tobramycin Eye Drops", "Tobramycin", "eye drops"],
  ["Moxifloxacin Eye Drops", "Moxifloxacin", "eye drops"],
  ["Carboxymethylcellulose Eye Drops", "Carboxymethylcellulose", "eye drops"],
];
